[package]
name = "tree-sitter-wisp"
version = "0.1.0"
edition = "2021"
license = "MIT"
readme = "README.md"
repository = "https://github.com/sullux/wisp"

[lib]
crate-type = ["cdylib"]
name = "tree_sitter_wisp"
path = "bindings/rust/lib.rs"

[dependencies]
tree-sitter = "0.20"
zed_extension_api = "0.1.0"

[build-dependencies]
cc = "1.0"